# Default state for all rules
default: true

options:
  frontMatter: true

# MD010/no-hard-tabs - Hard tabs
MD010:
  spaces_per_tab: 4

MD007:
  indent: 2

# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading/no-duplicate-header
MD024: false

# List numbering
MD029: false

# MD033/no-inline-html - Inline HTML
MD033: false

# First line in a file should be a top-level heading
MD041: false

# Code block style expect indented
MD046: false

# Emphasis style
MD049: "underscore"

# Space after list marker - needed for prettier linter
MD030: false

MD055:
  style: "leading_and_trailing"