name: Report readability

on: pull_request
jobs:
  report-readability:
    name: Report readability
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0
      - uses: Rebilly/lexi@v2
        with:
          github-token: ${{ secrets.PR_TOKEN }}
          glob: "**/*.md"
