name: Lint Markdown files

concurrency:
  group: pullrequest-untrusted-markdownlint-${{ github.event.number }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:

jobs:
  markdown_lint:
    name: Check Markdown files
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: .markdownlint.yaml
          search_paths: |
            docs/
